let csrf='',current=null,allRows=[];
const $=s=>document.querySelector(s), stages=[['upload','上传账单','↥'],['normalization','归一化','▤'],['classification','Jev 判断与分类','✳'],['preview','Notion 核对与导入','↗']];
async function api(path,body){const r=await fetch(path,{method:'POST',headers:{'Content-Type':'application/json','X-Flow-CSRF':csrf},body:JSON.stringify(body||{})});let v=await r.json();if(!r.ok)throw Error(v.error||'请求失败');return v}
function toast(s){const t=$('#toast');t.textContent=s;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2600)}
function show(which){$('#welcome').classList.toggle('hidden',which!=='welcome');$('#workspace').classList.toggle('hidden',which!=='workspace');$('#history').classList.toggle('hidden',which!=='history')}
function statusLabel(s){return({pending:'待处理',success:'已完成',blocked:'待审核',error:'失败',running:'处理中'})[s]||s||'待处理'}
function draw(){if(!current)return;if(['review','category_review'].includes(current.stage))current.stage='classification';show('workspace');$('#runTitle').textContent=current.month+' 账单';$('#runMeta').textContent=`${current.platforms.map(x=>x==='wechat'?'微信支付':'支付宝').join('、')} · 创建于 ${new Date(current.created_at).toLocaleString()}`;const st=current.stages;$('#runBadge').textContent=current.stage==='complete'?'已完成':statusLabel(st[current.stage]?.status);$('#canvas').innerHTML=stages.map(([k,n,icon])=>{const s=k==='preview'&&current.stage==='import'?st.import:(st[k]||{}),cls=s.status||'',desc=k==='upload'?`${s.count||0} 个账单文件`:k==='normalization'?`${s.count||0} 笔交易`:k==='classification'?`${s.count||0} 笔交易 · Jev 自动判断`:current.stage==='import'?s.status==='success'?'导入完成':'预览已核对，等待确认':'预览尚未生成';return `<div class="node ${cls} ${current.stage===k||k==='preview'&&current.stage==='import'?'active':''}" data-stage="${k}"><div class="node-icon">${icon}</div><b>${n}</b><small>${desc}${s.error?'<br>查看错误':''}</small></div>`}).join('');document.querySelectorAll('.node').forEach(n=>n.onclick=()=>openStage(n.dataset.stage==='preview'&&current.stage==='import'?'import':n.dataset.stage));openStage(current.stage)}
async function refreshRows(file='normalized.csv'){const v=await fetch(`/api/runs/${current.id}/rows?file=${file}`).then(r=>r.json());if(!v.rows)throw Error(v.error||'读取交易记录失败');allRows=v.rows}
async function openStage(k){const p=$('#panel'),s=current.stages[k];if(!s||(s.status==='pending'&&!['classification','preview','import'].includes(k))){p.classList.add('hidden');return}p.classList.remove('hidden');let title='',desc='',body='',actions='';
if(k==='upload'||k==='normalization'){title=k==='upload'?'已接收账单':'账单归一化';desc=s.error||`${s.count||0} 笔记录 · ${statusLabel(s.status)}`;if(s.summary)desc=`共 ${s.count} 笔，账单月份外 ${s.summary.outside_month} 笔`;if(k==='normalization'&&s.status==='error')actions='<button class="primary" id="retryNormalize">重试归一化</button>';}
if(k==='review'){title='交易复核';desc='以下记录因交易状态未识别、用途不明确或缺少必要信息而需要人工确认。选择处理方式；支出还需选择类别。';if(s.status==='error')desc=s.error;await refreshRows('normalized.csv');const pending=allRows.map((r,i)=>({r,i})).filter(x=>x.r.kind==='review');const mismatch=pending.length!==s.count;const categories=['Food','Housing','Transportation','Academics','Shopping','Entertainment','Health','Subscribe','Other'];const rows=pending.map(({r,i})=>`<div class="row review-row"><div><span class="row-title">${esc(r.party||r.item||r.type)}</span><small>${esc(r.time)} · ¥${esc(r.amount_yuan)}</small><small>${esc(r.item||'无商品说明')}</small></div><div><span>${esc(r.source==='wechat'?'微信支付':'支付宝')} · ${esc(r.method||'支付方式未知')}</span><small>${esc(r.type)} · ${esc(r.direction)} · ${esc(r.status)}</small><small>${esc(r.reason)}</small></div><select data-kind="row-${i}"><option value="">选择处理方式…</option><option value="expense">支出</option><option value="income">收入</option><option value="refund">退款</option><option value="transfer">转账</option><option value="exclude">排除</option></select><select data-category="row-${i}" disabled><option value="">选择支出类别…</option>${categories.map(c=>`<option value="${c}">${c}</option>`).join('')}</select></div>`).join('');body=mismatch?`<div class="status">状态记录显示 ${s.count} 笔待复核，账单实际有 ${pending.length} 笔。请重新同步状态。</div>${rows}`:pending.length?rows:'<div class="status ok">交易复核已完成</div>';if(mismatch)actions='<button class="primary" id="retryNormalize">重新同步复核状态</button>';else if(pending.length)actions='<button class="primary" id="saveReview">保存复核并继续</button>';}
if(k==='classification'){title='Jev 自动判断与分类';desc=s.error||`${s.count||0} 笔交易由 Jev 自动判断交易方式，并为支出选择类别。`;if(s.kind_counts)desc+=` 支出 ${s.kind_counts.expense||0} · 收入 ${s.kind_counts.income||0} · 退款 ${s.kind_counts.refund||0} · 转账 ${s.kind_counts.transfer||0} · 排除 ${s.kind_counts.exclude||0}`;if(s.local_rule_exclusions)desc+=` 亲情卡本地排除 ${s.local_rule_exclusions} 笔；`;if(s.local_account_overrides)desc+=` 花呗账户本地识别 ${s.local_account_overrides} 笔。`;if(s.status==='error')actions='<button class="primary" id="retryClassify">重试 Jev</button>';else if(current.stage==='classification'||s.status==='pending')actions='<button class="primary" id="doClassify">运行 Jev <span>→</span></button>';if(s.progress)body=jevProgress(s.progress);if(s.status==='success'&&(await refreshRows('classified.csv'),true))body=jevResults(allRows);}
if(k==='category_review'){title='分类审核';desc='查看 Jev 建议与概率，并为待确认记录选择最终类别。';await refreshRows('classified.csv');const rows=allRows.map((r,i)=>r.category==='Review'?`<div class="row"><div><span class="row-title">${esc(r.party||r.item||r.type)}</span><small>${esc(r.item)} · ¥${esc(r.amount_yuan)}</small></div><div><span class="prob">${esc(r.category_suggestion)} · ${(Number(r.category_probability||0)*100).toFixed(1)}%</span><small>${esc(r.category_review_reason)}</small></div><select data-key="row-${i}"><option value="">选择类别…</option>${['Food','Housing','Transportation','Academics','Shopping','Entertainment','Health','Subscribe','Other'].map(c=>`<option value="${c}">${c}</option>`).join('')}</select><div>${esc(r.party)}</div></div>`:'').join('');body=rows||'<div class="status ok">交易复核已完成</div>';if(s.count)actions='<button class="primary" id="saveCategories">保存类别并继续</button>';}
if(k==='preview'){title='Notion 核对与导入';desc=s.error||'生成预览只读取 Notion，不会写入；核对结果后可在此单独确认导入。';if(s.result)body=`<div class="summary">${Object.entries(s.result).map(([key,val])=>`<div><small>${esc(notionActionLabel(key))}</small><b>${esc(val)}</b></div>`).join('')}</div>`;if(s.progress)body=notionProgress(s.progress);if(s.status!=='running'&&(current.stage==='preview'||s.status==='pending'||s.status==='error'))actions=`<button class="primary" id="doPreview">${s.status==='error'?'重试预览':'生成导入预览'} <span>→</span></button>`;}
if(k==='import'){title='确认写入 Notion';desc=s.error|| (s.status==='success'?'导入完成。': '确认后将按预览结果写入 Notion。');if(s.result)body=`<div class="summary">${Object.entries(s.result).map(([key,val])=>`<div><small>${esc(notionActionLabel(key))}</small><b>${esc(val)}</b></div>`).join('')}</div>`;if(current.stage==='import'&&s.status!=='success')actions=`<button class="primary" id="doImport">${s.status==='error'?'重试导入':'确认导入 Notion'} <span>→</span></button>`;}
p.innerHTML=`<div class="panel-head"><div><h3>${title}</h3><p>${desc}</p></div><div class="panel-actions">${actions}</div></div>${body?`<div class="rows">${body}</div>`:''}`;
const submit=async(btn,fn)=>{btn.disabled=true;try{current=await fn();draw()}catch(e){toast(e.message);btn.disabled=false}};
$('#doClassify, #retryClassify')&&['doClassify','retryClassify'].forEach(id=>$('#'+id)?.addEventListener('click',e=>runJev(e.currentTarget)));
$('#retryNormalize')?.addEventListener('click',e=>submit(e.currentTarget,()=>api(`/api/runs/${current.id}/normalize`)));
$('#saveReview')?.addEventListener('click',e=>{const edits={};p.querySelectorAll('[data-kind]').forEach(x=>{const key=x.dataset.kind,category=p.querySelector(`[data-category="${key}"]`)?.value||'';if(x.value)edits[key]={kind:x.value,...(category?{category}:{})};if(x.value==='expense'&&!category)x.dataset.missing='category'});if(Object.keys(edits).length!==s.count)return toast('请为每笔待审核交易选择处理方式');if(p.querySelector('[data-missing="category"]')){p.querySelectorAll('[data-missing]').forEach(x=>delete x.dataset.missing);return toast('请为支出选择类别')}submit(e.currentTarget,()=>api(`/api/runs/${current.id}/review`,{edits}))});
 p.querySelectorAll('[data-kind]').forEach(x=>x.addEventListener('change',()=>{const category=p.querySelector(`[data-category="${x.dataset.kind}"]`);category.disabled=x.value!=='expense';if(x.value!=='expense')category.value=''}));
$('#saveCategories')?.addEventListener('click',e=>{const edits={};p.querySelectorAll('select').forEach(x=>{if(x.value)edits[x.dataset.key]={category:x.value}});if(Object.keys(edits).length!==s.count)return toast('请为每笔待确认交易选择类别');submit(e.currentTarget,()=>api(`/api/runs/${current.id}/categories`,{edits}))});
$('#doPreview')?.addEventListener('click',e=>runPreview(e.currentTarget));
$('#doImport')?.addEventListener('click',e=>{if(!confirm('确定按当前预览结果写入 Notion？'))return;submit(e.currentTarget,()=>api(`/api/runs/${current.id}/import`))});}
function kindLabel(kind){return({expense:'支出',income:'收入',refund:'退款',transfer:'转账',exclude:'排除'})[kind]||kind}
function accountLabel(a){return({source_wallet:'平台钱包',bank_account:'银行卡账户',huabei:'花呗账户',unknown:'无法识别'})[a]||a||'—'}
function jevProgress(progress){const latest=(progress.latest||[]).map(r=>`<div class="decision-row"><b>${esc(r.party||r.item||'未注明交易')}</b><span>${kindLabel(r.kind)}${r.kind==='expense'?' · '+esc(r.category):''}</span><small>${esc(accountLabel(r.account))} · 账户 ${(Number(r.account_probability)*100).toFixed(1)}%</small></div>`).join('');return `<div id="jevLive"><progress max="${progress.total||1}" value="${progress.done||0}"></progress><b>${progress.done||0} / ${progress.total||0} 笔</b><div class="decision-list">${latest||'<div class="muted">等待 Jev 返回第一笔判断…</div>'}</div></div>`}
function jevResults(rows){const counts={expense:0,income:0,refund:0,transfer:0,exclude:0};const html=rows.map(r=>{counts[r.kind]=(counts[r.kind]||0)+1;return `<div class="decision-row"><b>${esc(r.party||r.item||'未注明交易')}</b><span>${kindLabel(r.kind)}${r.kind==='expense'?' · '+esc(r.category):''}</span><small>${esc(accountLabel(r.account_suggestion))} · 账户 ${(Number(r.account_probability)*100).toFixed(1)}%</small></div>`}).join('');return `<div class="decision-summary">${Object.entries(counts).map(([k,v])=>`<span>${kindLabel(k)} ${v}</span>`).join('')}</div><div class="decision-list">${html}</div>`}
function notionActionLabel(key){return({create_subscription:'新增订阅',create_huabei_repayment:'新增花呗还款转账',update_account:'更新账户关联'})[key]||key}
function notionProgress(progress){const actions=progress.actions||{},pct=progress.total?Math.round(progress.done/progress.total*100):0;return `<div id="notionLive"><b>${esc(progress.phase||'准备中')} · ${progress.phase_index||0}/${progress.phase_count||5}</b>${progress.phase==='核对账单'?`<progress max="${progress.total||1}" value="${progress.done||0}"></progress><small>${progress.done||0} / ${progress.total||0} 笔（${pct}%）</small>`:''}<p class="muted">${esc(progress.detail||'等待 Notion 响应…')}${progress.latest?` · ${esc(progress.latest)}`:''}</p><div class="decision-summary">${Object.entries(actions).map(([k,v])=>`<span>${esc(notionActionLabel(k))} ${esc(Array.isArray(v)?v.length:v)}</span>`).join('')}</div></div>`}
async function runPreview(btn){btn.disabled=true;btn.textContent='正在查询 Notion…';if(!$('#notionLive'))$('#panel').insertAdjacentHTML('beforeend',`<div class="rows">${notionProgress({})}</div>`);let result,error,done=false;const task=api(`/api/runs/${current.id}/preview`).then(v=>result=v).catch(e=>error=e).finally(()=>done=true);while(!done){await new Promise(resolve=>setTimeout(resolve,700));if(done)break;try{current=await fetch(`/api/runs/${current.id}`).then(r=>r.json());const live=$('#notionLive');if(live)live.outerHTML=notionProgress(current.stages.preview?.progress||{});}catch(_){}}await task;if(error){try{current=await fetch(`/api/runs/${current.id}`).then(r=>r.json());draw()}catch(_){toast(error.message)}return}current=result;draw()}
async function runJev(btn){btn.disabled=true;btn.textContent='Jev 判断中…';if(!$('#jevLive'))$('#panel').insertAdjacentHTML('beforeend',`<div class="rows">${jevProgress({})}</div>`);let result,error,done=false;const task=api(`/api/runs/${current.id}/classify`).then(v=>result=v).catch(e=>error=e).finally(()=>done=true);while(!done){await new Promise(resolve=>setTimeout(resolve,700));if(done)break;try{current=await fetch(`/api/runs/${current.id}`).then(r=>r.json());const live=$('#jevLive');if(live)live.outerHTML=jevProgress(current.stages.classification?.progress||{});}catch(_){}}await task;if(error){toast(error.message);btn.disabled=false;btn.textContent='重试 Jev';return}current=result;draw()}
function esc(x){return String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function openDialog(){$('#formError').textContent='';const d=$('#newDialog');d.showModal();const m=new Date();$('#newForm [name=month]').value=`${m.getFullYear()}-${String(m.getMonth()+1).padStart(2,'0')}`}
$('#newBtn').onclick=$('#startBtn').onclick=openDialog;$('#closeDialog').onclick=()=>$('#newDialog').close();
$('#newForm').onsubmit=async e=>{e.preventDefault();const fd=new FormData(e.currentTarget);if(!fd.getAll('wechat').some(x=>x.size)&&!fd.getAll('alipay').some(x=>x.size)){return $('#formError').textContent='请至少选择一份账单'}const btn=e.submitter;btn.disabled=true;btn.textContent='上传并处理中…';$('#formError').textContent='文件上传后会立即整理账单，请稍候。';try{const r=await fetch('/api/runs',{method:'POST',headers:{'X-Flow-CSRF':csrf},body:fd});const v=await r.json();if(!r.ok)throw Error(v.error||'上传失败');current=v;$('#newDialog').close();draw();toast('账单已上传')}catch(err){$('#formError').textContent=err.message||'上传失败，请重试'}finally{btn.disabled=false;btn.innerHTML='上传并开始 <span>→</span>'}};
async function history(){show('history');const list=await fetch('/api/runs').then(r=>r.json());$('#historyList').innerHTML=list.length?list.map(r=>`<div class="history-item" data-id="${r.id}"><div><b>${esc(r.month)} 账单 · ${r.platforms.map(x=>x==='wechat'?'微信支付':'支付宝').join('、')}</b><small>${new Date(r.created_at).toLocaleString()} · ${esc(r.stage)}</small></div><span class="badge">${r.stage==='complete'?'已完成':statusLabel(r.stages[r.stage]?.status)}</span></div>`).join(''):'<div class="panel muted">还没有运行记录</div>';document.querySelectorAll('.history-item').forEach(x=>x.onclick=async()=>{current=await fetch(`/api/runs/${x.dataset.id}`).then(r=>r.json());draw()})}
$('#historyNav').onclick=history;$('#backBtn').onclick=()=>current?draw():show('welcome');
async function init(){const s=await fetch('/api/session').then(r=>r.json());csrf=s.csrf;document.cookie=`flow_csrf=${csrf}; SameSite=Strict; Path=/`;const list=await fetch('/api/runs').then(r=>r.json());if(list.length){current=await fetch(`/api/runs/${list[0].id}`).then(r=>r.json());draw()}else show('welcome')}
init().catch(e=>toast(e.message));
